version: "3.3"

services:
  watches-api:
    container_name: watches-api
    restart: always
    image: node:20.10.0
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    ports:
      - 4001:3009
    volumes:
      - ./:/usr/src/watches
    working_dir: /usr/src/watches
    networks:
      - monorepo-network
    command: bash -c "npm install --include=dev && npm run build:api && npm run start:api:prod"

  watches-batch:
    container_name: watches-batch
    restart: unless-stopped
    image: node:20.10.0
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    ports:
      - 4002:3001
    volumes:
      - .:/usr/src/watches
    working_dir: /usr/src/watches
    networks:
      - monorepo-network
    command: bash -c "npm install --include=dev && npm run build:batch && npm run start:batch:prod"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - monorepo-network    # ✅ plain string, no colon

networks:
  monorepo-network:         # ✅ driver goes here at the top level
    driver: bridge