version: "3.3"

services:
  watches-api:
    container_name: watches-api
    restart: always
    image: node:20.10.0
    environment:
      - NODE_ENV=production
    ports:
      - 4001:3009
    volumes:
      - ./:/usr/src/watches
    working_dir: /usr/src/watches

    networks:
      - monorepo-network

      
  # FOR PRODUCTION
    command: bash -c "npm install --include=dev && npm run build:api && npm run start:api:prod"

  watches-batch:
    container_name: watches-batch
    restart: unless-stopped
    image: node:20.10.0
    environment:
      - NODE_ENV=production
    ports:
      - 4002:3001
    volumes:
      - .:/usr/src/watches
    working_dir: /usr/src/watches

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install --include=dev && npm run build:batch && npm run start:batch:prod"

networks:
  monorepo-network:
    driver: bridge









    # timeless-next: locahost:4000 => container: 3000
    # watches-api: localhost:4001 => container: 3009
    # watches-batch: localhost:4002 => container: 3001